server:
 port: 9000
spring: 
 cloud:
  gateway:
   routes:
   - id: jsonplaceholder
     uri: https://jsonplaceholder.typicode.com
     predicates:
      Path=/todos/**
   - id: reqres
     uri: https://reqres.in
     predicates:
      Path=/api/**
   - id: httpbin
     uri: https://httpbin.org
     predicates:
      Path=/get/**
   globalcors:
    cors-configurations:
     '[/**]':
       allowedOrigins: "*"
       allowedMethods:
       - GET
       - PUT
       - DELETE
       - POST
